base/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('coder.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]

usuarios/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from usuarios import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registro/', views.registro, name='registro'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('editar-perfil/', views.editar_perfil, name='editar_perfil'),
    path('cambio-contrasenia/', views.CambioContrasenia.as_view(), name='cambio_contrasenia')
]

usuarios/models.py
from django.db import models

from django.contrib.auth.models import User


# Create your models here.
class InformacionExtra(models.Model):
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class MiFormularioDeCreacion(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contrasenia', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir Contrasenia', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k: '' for k in fields}

class EdicionDatosUsuario(UserChangeForm):
    password = None
    email = forms.EmailField()
    first_name = forms.CharField(label='Nombre', max_length=20)
    last_name = forms.CharField(label='Apellido', max_length=20)
    avatar = forms.ImageField(required=False)
    
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'avatar']

usuarios/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as django_login
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from usuarios.models import InformacionExtra
from usuarios.forms import EdicionDatosUsuario

def login(request):
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            nombre_usuario = formulario.cleaned_data.get('username')
            contrasenia = formulario.cleaned_data.get('password')
            usuario = authenticate(username=nombre_usuario, password=contrasenia)
            django_login(request, usuario)
            InformacionExtra.objects.get_or_create(user=request.user)
            return redirect('inicio')
        else:
            return render(request, 'usuarios/login.html', {'formulario': formulario})
            

    formulario = AuthenticationForm()
    return render(request, 'usuarios/login.html', {'formulario': formulario})

def registro(request):
    if request.method == "POST":
        formulario = UserCreationForm(request.POST)
        # formulario = MiFormularioDeCreacion(request.POST)

        if formulario.is_valid():
            formulario.save()
            return redirect('usuarios:login')
        else:
            return render(request, 'usuarios/registro.html', {'formulario': formulario})

    formulario = UserCreationForm()
    # formulario = MiFormularioDeCreacion()
    return render(request, 'usuarios/registro.html', {'formulario': formulario})

@login_required
def editar_perfil(request):
    if request.method == "POST":
        formulario = EdicionDatosUsuario(request.POST, request.FILES, instance=request.user)
        
        if formulario.is_valid():
            if formulario.cleaned_data.get('avatar'):
                request.user.informacionextra.avatar = formulario.cleaned_data.get('avatar')
            request.user.informacionextra.save()
            formulario.save()
            return redirect('inicio')
        else:
            return render(request, 'usuarios/editar_perfil.html', {'formulario': formulario})
            
    formulario = EdicionDatosUsuario(initial={'avatar': request.user.informacionextra.avatar}, instance=request.user)
    return render(request, 'usuarios/editar_perfil.html', {'formulario': formulario})
    
    
class CambioContrasenia(PasswordChangeView):
    template_name = 'usuarios/cambiar_contrasenia.html'
    success_url = reverse_lazy('usuarios:editar_perfil')

templates/usuarios/cambiar_contrasenia.html
{% extends 'base.html' %}

{% block contenido_title %}
<title>Editar Perfil</title>
{% endblock contenido_title %}

{% block contenido_header %}
    <h1 class="mb-5">Editar Perfil</h1>
{% endblock contenido_header %}


{% block contenido %}

{% if form.errors %}
<p style="color: red">Hay errores</p>
{% endif %}

<form action={% url 'usuarios:cambio_contrasenia' %} method="post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Cambiar</button>
</form>
{% endblock contenido %}

templates/usuarios/editar_perfil.html
{% extends 'base.html' %}

{% block contenido_title %}
<title>Editar Perfil</title>
{% endblock contenido_title %}

{% block contenido_header %}
    <h1 class="mb-5">Editar Perfil</h1>
{% endblock contenido_header %}


{% block contenido %}

{% if formulario.errors %}
<p style="color: red">Hay errores</p>
{% endif %}

<form action='' method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button type='button'><a class="navbar-brand" href={% url 'usuarios:cambio_contrasenia' %}>Cambiar contrasenia</a></button>
    <button>Guardar cambios</button>
</form>
{% endblock contenido %}

templates/usuarios/login.html
{% extends 'base.html' %}

{% block contenido_title %}
<title>Iniciar Sesion</title>
{% endblock contenido_title %}

{% block contenido_header %}
    <h1 class="mb-5">Iniciar Sesion</h1>
{% endblock contenido_header %}


{% block contenido %}
{% if formulario.errors %}
<p style="color: red">Hay errores</p>
{% endif %}

<form action={% url 'usuarios:login' %} method="post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Iniciar Sesion</button>
</form>
{% endblock contenido %}

templates/usuarios/logout.html
{% extends 'base.html' %}

{% block contenido_title %}
<title>Logout</title>
{% endblock contenido_title %}

{% block contenido_header %}
    <h1 class="mb-5">Has cerrado sesión con éxito</h1>
{% endblock contenido_header %}


{% block contenido %}

<p style="color: green">Has cerrado sesión con éxito</p>

{% endblock contenido %}

templates/usuarios/registro.html
{% extends 'base.html' %}

{% block contenido_title %}
<title>Registrarse</title>
{% endblock contenido_title %}

{% block contenido_header %}
    <h1 class="mb-5">Registrarse</h1>
{% endblock contenido_header %}


{% block contenido %}

{% if formulario.errors %}
<p style="color: red">Hay errores</p>
{% endif %}

<form action={% url 'usuarios:registro' %} method="post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Registrarse</button>
</form>
{% endblock contenido %}