base/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('coder.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]

usuarios/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from usuarios import views

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registro/', views.registro, name='registro'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('editar-perfil/', views.editar_perfil, name='editar_perfil'),
    path('cambio-contrasenia/', views.CambioContrasenia.as_view(), name='cambio_contrasenia')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block contenido_title %}
        <title>Landing Page - Start Bootstrap Theme</title>
        {% endblock  %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'inicio' %}">Inicio</a>
                <a class="navbar-brand" href="{% url 'estudiantes' %}">Estudiantes</a>
                <a class="navbar-brand" href="{% url 'cursos' %}">Cursos</a>
                <a class="navbar-brand" href="{% url 'profesores' %}">Profesores</a>
                <a href="{% url 'usuarios:editar_perfil' %}">{{request.user.username}}</a>
                {% if request.user.is_authenticated %}
                    {% if request.user.informacionextra.avatar %}
                        <img src={{request.user.informacionextra.avatar.url}} alt="" height="40px">
                    {% endif %}
                <a class="btn btn-primary" href="{% url 'usuarios:logout' %}">Cerrar Sesión</a>
                {% else %}
                <a class="btn btn-primary" href="{% url 'usuarios:login' %}">Iniciar Sesión</a>
                <a class="btn btn-primary" href={% url 'usuarios:registro' %}>Registrarse</a>
                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            {% block contenido_header %}
                            <h1 class="mb-5">Generate more leads with a professional landing page!</h1>
                            {% endblock contenido_header %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block contenido %}
        
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/crear_cursos.html
{% extends 'base.html' %}

{% block contenido_title %}
<title>Crear curso</title>
{% endblock contenido_title %}

{% block contenido_header %}
    <h1 class="mb-5">Crear curso</h1>
{% endblock contenido_header %}


{% block contenido %}
<form action={% url 'crear_cursos' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    {% comment %} <input type="submit" value="Crear"> {% endcomment %}
    <button>Crear</button>
</form>
{% endblock contenido %}

templates/cursos.html
{% extends 'base.html' %}

{% block contenido_title %}
        <title>Cursos</title>
{% endblock  %}
{% block contenido_header %}
        <h1 class="mb-5">Bienvenido a los Cursos</h1>
{% endblock contenido_header %}

{% block contenido %}
        {% if cursos %}
                {% for curso in cursos %}
                        <li>{{curso.comision}} - {{curso.lenguaje}}</li>
                {% endfor %}
        {% else %}
                <h2>No hay datos sobre cursos por el momento.</h2>
        {% endif %}
        <a class="navbar-brand" href={% url 'crear_cursos' %}>Crear Cursos</a>
{% endblock contenido %}

templates/cursos_crear.html
{% extends 'base.html' %}

{% block contenido_title %}
<title>Crear curso</title>
{% endblock contenido_title %}

{% block contenido_header %}
    <h1 class="mb-5">Crear curso</h1>
{% endblock contenido_header %}


{% block contenido %}
<form action={% url 'crear_cursos' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    {% comment %} <input type="submit" value="Crear"> {% endcomment %}
    <button>Crear</button>
</form>
{% endblock contenido %}

templates/cursos_modificar.html
{% extends 'base.html' %}

{% block contenido_title %}
        <title>Modificar Cursos</title>
{% endblock  %}
{% block contenido_header %}
        <h1 class="mb-5">Modificar Curso</h1>
{% endblock contenido_header %}

{% block contenido %}
<form action={% url 'modificar_cursos' id_curso %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Modificar</button>
</form>
{% endblock contenido %}

templates/cursos_mostrar.html
{% extends 'base.html' %}

{% block contenido_title %}
        <title>Cursos</title>
{% endblock  %}
{% block contenido_header %}
        <h1 class="mb-5">{{curso_a_mostrar}}</h1>
{% endblock contenido_header %}

{% block contenido %}
<ul>
    <li>Comision: {{curso_a_mostrar.comision}}</li>
    <li>Lenguaje: {{curso_a_mostrar.lenguaje}}</li>
</ul>
<p>
    <button>
        <a class="navbar-brand" href={% url 'modificar_cursos' curso_a_mostrar.id %}>Modificar</a>
    </button>
    <button>
        <a class="navbar-brand" href={% url 'eliminar_cursos' curso_a_mostrar.id %}>Eliminar</a>
    </button>
</p> 
{% endblock contenido %}

templates/estudiantes.html
{% extends 'base.html' %}

{% block contenido_title %}
        <title>Estudiantes</title>
{% endblock  %}
{% block contenido_header %}
        <h1 class="mb-5">Bienvenido a la pagina de Estudiantes</h1>
{% endblock contenido_header %}

{% block contenido %}
        {% if estudiantes %}
                {% for estudiante in estudiantes %}
                        <li>
                                <a class="navbar-brand" href={% url 'mostrar_estudiantes' estudiante.id %}>{{estudiante.nombre}} - {{estudiante.edad}}</a>
                                <button>
                                        <a class="navbar-brand" href={% url 'modificar_estudiantes' estudiante.id %}>Modificar</a>
                                </button>
                                <button>
                                        <a class="navbar-brand" href={% url 'eliminar_estudiantes' estudiante.id %}>Eliminar</a>
                                </button>
                        </li>
                {% endfor %}
        {% else %}
                <h2>No hay datos sobre estudiantes por el momento.</h2>
        {% endif %}
        <a class="navbar-brand" href={% url 'crear_estudiantes' %}>Crear un estudiante</a>
{% endblock contenido %}

templates/estudiantes_modificar.html
{% extends 'base.html' %}

{% block contenido_title %}
        <title>Modificar Estudiante</title>
{% endblock  %}
{% block contenido_header %}
        <h1 class="mb-5">Modificar Estudiante</h1>
{% endblock contenido_header %}

{% block contenido %}
<form action={% url 'modificar_estudiantes' id_estudiante %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Modificar</button>
</form>
{% endblock contenido %}

templates/estudiantes_mostrar.html
{% extends 'base.html' %}

{% block contenido_title %}
        <title>Estudiante</title>
{% endblock  %}
{% block contenido_header %}
        <h1 class="mb-5">{{estudiante_a_mostrar}}</h1>
{% endblock contenido_header %}

{% block contenido %}
<ul>
    <li>Nombre: {{estudiante_a_mostrar.nombre}}</li>
    <li>Edad: {{estudiante_a_mostrar.edad}}</li>
</ul>
<p>
    <button>
        <a class="navbar-brand" href={% url 'modificar_estudiantes' estudiante_a_mostrar.id %}>Modificar</a>
    </button>
    <button>
        <a class="navbar-brand" href={% url 'eliminar_estudiantes' estudiante_a_mostrar.id %}>Eliminar</a>
    </button>
</p>
{% endblock contenido %}

templates/index.html
{% extends 'base.html' %}

{% block contenido_title %}
<title>Bienvenido</title>
{% endblock  %}

{% block contenido_header %}
<h1 class="mb-5">Coder App</h1>
{% endblock contenido_header %}

templates/profesores.html
{% extends 'base.html' %}

{% block contenido_title %}
        <title>Estudiantes</title>
{% endblock  %}
{% block contenido_header %}
        <h1 class="mb-5">Bienvenido a la pagina de Profesores</h1>
{% endblock contenido_header %}

templates/prueba_render.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prueba render</title>
</head>
<body>
    <h1>Probando render de {{nombre}}!</h1>
</body>
</html>